apiVersion: v1
kind: Template
metadata:
  name: shopping-cart-template
  annotations:
    description: "Shopping Cart Template"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: shopping-cart-${APP_ENVIRONMENT}
    spec:
      selector:
        matchLabels:
          app: shopping-cart-${APP_ENVIRONMENT}
      replicas: 1
      template:
        metadata:
          labels:
            app: shopping-cart-${APP_ENVIRONMENT}
        spec:
          containers:
            - name: shopping-cart-${APP_ENVIRONMENT}
              image: quay.io/${QUAY_USER_OR_GROUP}/do400-deploying-environments:${APP_IMAGE_TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
      strategy:
        type: RollingUpdate
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: shopping-cart-${APP_ENVIRONMENT}
      name: shopping-cart-${APP_ENVIRONMENT}
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: shopping-cart-${APP_ENVIRONMENT}
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: shopping-cart-${APP_ENVIRONMENT}
      labels:
        app: shopping-cart-${APP_ENVIRONMENT}
    spec:
      to:
        kind: Service
        name: shopping-cart-${APP_ENVIRONMENT}
      port:
        targetPort: 8080

parameters:
  - name: QUAY_USER_OR_GROUP
    description: "Quay User/Group"
    required: true
  - name: APP_ENVIRONMENT
    description: "Application environment"
    required: false
    value: "stage"
  - name: APP_IMAGE_TAG
    description: "Image Tag"
    required: false
    value: "1.0-SNAPSHOT"